---
title: "MONIPOLLI - MAS 2024"
author: "Emma Cartuyvels"
format: 
  html:
    code-fold: true
    toc: true
    toc_float: true
    embed-resources: true
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE)
```

```{r set-up}
library(here)
library(sf)
library(ggpubr)
library(lme4)
library(tidyverse)
library(INBOtheme)

conflicted::conflicts_prefer(dplyr::filter)
```

## Read data

```{r}
beheer_data <- read_csv(here("data", "processed", "bestuivers_2024"))
```

```{r}
mas_data <- read.csv(here("data", "mas_data_vlaanderen_2018_2024.csv")) |> 
  filter(is_mas_sample == TRUE, #(om enkel correcte MAS-protocol data te behouden)
         year == 2024)
```

```{r}
locations <- beheer_data |>
  distinct(pointid) |>
  pull()

mas_filtered <- mas_data |>
  filter(locationID %in% locations,
         organismQuantityType != "individuals") |>
  mutate(organismQuantity = 1)
```

```{r}
grouped_poll <- beheer_data |>
  group_by(order, pointid) |>
  summarise(n_spec = n_distinct(species_nm),
            n_ind = sum(n_ind))

grouped_mas <- mas_filtered |>
  group_by(locationID) |>
  summarise(n_spec = n_distinct(scientificName),
            n_ind = sum(organismQuantity))
```

## Verkennende analyses
### Wilde bijen versus vogels

```{r}
grouped_poll |>
  filter(order == "Apoidea") |>
  left_join(grouped_mas , by = c("pointid" = "locationID"),
            suffix = c("_pol", "_mas")) |>
  ggplot(aes(x = n_ind_pol, y = n_ind_mas)) +
  geom_point() +
  stat_cor() +
  geom_smooth(method='lm')
```

```{r}
grouped_poll |>
  filter(order == "Apoidea") |>
  left_join(grouped_mas , by = c("pointid" = "locationID"),
            suffix = c("_pol", "_mas")) |>
  ggplot(aes(x = n_spec_pol, y = n_spec_mas)) +
  geom_point() +
  stat_cor() +
  geom_smooth(method='lm')
```

### Vlinders versus vogels

```{r}
grouped_poll |>
  filter(order == "Lepidoptera") |>
  left_join(grouped_mas , by = c("pointid" = "locationID"),
            suffix = c("_pol", "_mas")) |>
  ggplot(aes(x = n_ind_pol, y = n_ind_mas)) +
  geom_point() +
  stat_cor() +
  geom_smooth(method='lm')
```

```{r}
grouped_poll |>
  filter(order == "Lepidoptera") |>
  left_join(grouped_mas , by = c("pointid" = "locationID"),
            suffix = c("_pol", "_mas")) |>
  ggplot(aes(x = n_spec_pol, y = n_spec_mas)) +
  geom_point() +
  stat_cor() +
  geom_smooth(method='lm')
```

### Zweefvliegen versus vogels

```{r}
grouped_poll |>
  filter(order == "Syrphidae") |>
  left_join(grouped_mas , by = c("pointid" = "locationID"),
            suffix = c("_pol", "_mas")) |>
  ggplot(aes(x = n_ind_pol, y = n_ind_mas)) +
  geom_point() +
  stat_cor() +
  geom_smooth(method='lm')
```

### Alle bestuivers versus vogels

```{r}
grouped_poll |>
  group_by(pointid) |>
   summarise(n_spec = sum(n_spec),
            n_ind = sum(n_ind)) |>
  left_join(grouped_mas , by = c("pointid" = "locationID"),
            suffix = c("_pol", "_mas")) |>
  ggplot(aes(x = n_ind_pol, y = n_ind_mas)) +
  geom_point() +
  stat_cor() +
  geom_smooth(method='lm')
```

Voorlopig geen aantal soorten van zweefvliegen dus deze zitten er niet bij.

```{r}
grouped_poll |>
  filter(order != "Syrpidae") |>
  group_by(pointid) |>
   summarise(n_spec = sum(n_spec),
            n_ind = sum(n_ind)) |>
  left_join(grouped_mas , by = c("pointid" = "locationID"),
            suffix = c("_pol", "_mas")) |>
  ggplot(aes(x = n_spec_pol, y = n_spec_mas)) +
  geom_point() +
  stat_cor() +
  geom_smooth(method='lm')
```

## Modellering

```{r}
pollinators <- grouped_poll |>
  group_by(pointid) |>
  summarise(n_spec = sum(n_spec),
            n_ind = sum(n_ind))

jaar = "2024"

ver_var <- beheer_data |>
  distinct(pointid, openheid_sbp)

mod_dat <- mas_filtered |>
  mutate(
    datum = ymd(eventDate),
    periode_in_jaar = case_when(
      datum %within% interval(
        ymd(paste(jaar, "04-01", sep = "-")),
        ymd(paste(jaar, "04-20", sep = "-"))
      ) ~ "R1",
      datum %within% interval(
        ymd(paste(jaar, "04-21", sep = "-")),
        ymd(paste(jaar, "05-10", sep = "-"))
      ) ~ "R2",
      datum %within% interval(
        ymd(paste(jaar, "05-11", sep = "-")),
        ymd(paste(jaar, "06-10", sep = "-"))
      ) ~ "R3",
      datum %within% interval(
        ymd(paste(jaar, "06-21", sep = "-")),
        ymd(paste(jaar, "07-15", sep = "-"))
      ) ~ "R4"
    )
  ) |>
  filter(!is.na(.data$periode_in_jaar)) |> 
  group_by(locationID, periode_in_jaar) |>
  summarise(n_spec = n_distinct(scientificName),
            n_ind = sum(organismQuantity)) |>
  left_join(pollinators, by = c("locationID" = "pointid"),
            suffix = c("_bird", "_pol")) |>
  left_join(ver_var, by = c("locationID" = "pointid"))
```

```{r}
hist(log(mod_dat$n_ind_pol))

hist(mod_dat$n_spec_bird)

ggplot(mod_dat, aes(x = n_ind_pol, y =n_spec_bird)) +
  geom_point() +
  geom_smooth()
```


```{r}
model1 <- glmer(n_spec_bird ~ n_ind_pol + (1|locationID) + (1|periode_in_jaar),
                data = mod_dat,
                family = "poisson")
```

```{r}
performance::check_model(model1)
```

```{r}
summary(model1)
```


```{r}
model2 <- glmer(n_ind_bird ~ n_ind_pol + openheid_sbp + (1|locationID) +
                  (1|periode_in_jaar),
                data = mod_dat,
                family = "poisson")
```

```{r}
performance::check_model(model2)
```

```{r}
summary(model2)
```


```{r}
test <- glmer(n_spec_bird ~ scale(n_ind_pol) * openheid_sbp +
                (1|locationID) +
                (1|periode_in_jaar),
              data = mod_dat)

summary(test)

marginaleffects::plot_predictions(model = test, condition = c("n_ind_pol", "openheid_sbp"))

ggplot(mod_dat, aes(x = n_ind_pol, y =n_spec_bird, colour = openheid_sbp, group = openheid_sbp)) +
  geom_point() +
  geom_smooth(method = "lm") + theme_minimal()
```

```{r}
library(ggpmisc)

ggplot(mod_dat, aes(x = n_ind_pol, y = n_spec_bird)) +
  geom_point(aes(colour = openheid_sbp)) +
  geom_smooth(method = "lm", se = FALSE, aes(colour = openheid_sbp)) +
  facet_wrap(~ openheid_sbp) +
  stat_poly_eq(
    aes(label = paste(..eq.label.., ..p.value.label.., sep = "~~~")),
    formula = y ~ x,
    parse = TRUE,
    label.x.npc = "left", label.y.npc = 0.95,
    size = 3
  ) +
  labs(x = "Totaal aantal bestuivers", y = "Aantal soorten vogels") +
  theme_minimal()
```

```{r}
ggplot(mod_dat, aes(x = n_ind_pol, y = n_ind_bird)) +
  geom_point(aes(colour = openheid_sbp)) +
  geom_smooth(method = "lm", se = FALSE, aes(colour = openheid_sbp)) +
  facet_wrap(~ openheid_sbp) +
  stat_poly_eq(
    aes(label = paste(..eq.label.., ..p.value.label.., sep = "~~~")),
    formula = y ~ x,
    parse = TRUE,
    label.x.npc = "left", label.y.npc = 0.95,
    size = 3
  ) +
  labs(x = "Totaal aantal bestuivers", y = "Totaal aantal vogels") +
  theme_minimal()
```

